### ISSUE TITLE
No git version tags

### ISSUE THREAD

**Issue by kloczek** [Zac-HD/hypothesmith#14]
According to https://pypi.org/project/hypothesmith/ latest version is 0.1.8 however there is no in git repo version tags.
Is it possible to add version tag for last version?

**Comment by kloczek** [comment]
gentle ping ..

**Comment by Zac-HD** [comment]
My concern is that if it's not fully automated, I'm just not going to consistently remember to add tags, and I'm unwilling to complicate the current 'just push to master' release system.  As it says in the readme:

> This is definitely pre-alpha, but if you want to play with it feel free! You can even keep the shiny pieces when - not if - it breaks.

I'd recommend getting it off PyPI, not GitHub, and don't consider it mature enough to recommend repackaging.

**Comment by kloczek** [comment]
> My concern is that if it's not fully automated, I'm just not going to consistently remember to add tags, and I'm unwilling to complicate the current 'just push to master' release system. As it says in the readme:

Hmm moment .. what is so complicated with adding git tag after make the new release? 🤔 
At the moemtn there is no any tags.

Issue is that without tags using git it is hard to find out what has changed betwen versions and/or since last version.

**Comment by kloczek** [comment]
Gentle ping one more time ..

It would be really good to have version git tags because without those tags it is really hard to figure out what has changed between versions 😞
