### ISSUE TITLE
Grammar definition file handling is broken

### ISSUE THREAD

**Issue by AMDmi3** [Zac-HD/hypothesmith#26]
The very idea if fetching grammar definition file is broken

https://github.com/Zac-HD/hypothesmith/blob/167d3f42d7b710eb662b3af7387738367f33f6ef/src/hypothesmith/syntactic.py#L16-L25

It doesn't work offline (either physically, or forcibly, such as within sandboxed CI), it will break on transient network problems, it will break if the file is moved in lark repository or the repository itself is moved, it doesn't work when the directory where the __file__ is located is writable (e.g. case when hypothesmith is installed systemwide). hypothesmith should either install its own copy of the file, or point to the file which should be already installed by libcst.

Here's the patch for the latter solution I've used for FreeBSD port:
```diff
--- src/hypothesmith/syntactic.py.orig	2022-11-26 03:56:51 UTC
+++ src/hypothesmith/syntactic.py
@@ -7,24 +7,20 @@ import urllib.request
 from functools import lru_cache
 from pathlib import Path
 
+import lark.grammars
 from hypothesis import assume, strategies as st
 from hypothesis.extra.lark import LarkStrategy
 from hypothesis.internal.charmap import _union_intervals
 from lark import Lark
 from lark.indenter import Indenter
 
-URL = "https://raw.githubusercontent.com/lark-parser/lark/master/lark/grammars/python.lark"
-fname = Path(__file__).with_name(URL.split("/")[-1])
+fname = Path(lark.grammars.__file__).with_name('python.lark')
 
 if fname.exists():
     with open(fname) as f:
         lark_grammar = f.read()
 else:  # pragma: no cover
-    # To update the grammar definition, delete the file and execute this.
-    with urllib.request.urlopen(URL) as handle:
-        lark_grammar = handle.read().decode()
-    with open(fname, "w") as f:
-        f.write(lark_grammar)
+    raise RuntimeError(f'Grammar definition file not found at {fname}')
 
 COMPILE_MODES = {
     "eval_input": "eval",
```

**Comment by Zac-HD** [comment]
Fair; we never actually download this at runtime but a comment with the corresponding `wget` command would make it about as easy to update the grammar.  I'll also use `importlib.resources` over `Path` here then 🙂
