### ISSUE TITLE
Add release

### ISSUE THREAD

**Issue by FFY00** [Zac-HD/hypothesmith#6]
Would it be possible to add a release so this can be properly packaged? What is your roadmap?

**Comment by Zac-HD** [comment]
Hey @FFY00 - sorry I missed this when it was opened!

As a side-side-side project, Hypothesmith has a highly automated release system consisting of "try to upload every commit on `master` to PyPI" - which is a noop if the version number hasn't been updated.  Sadly I don't have a convenient way to tag releases from this system, though I imagine that it could be done with a fairly short shell script.

There is also no roadmap.  I'd like to publish a paper on it at some point ([notes here](https://zhd.dev/phd/hypothesmith.html)) and also to keep improving it, but neither is my top priority now or for the foreseeable future.
