### ISSUE TITLE
hypothesmith powered testing for isort

### ISSUE THREAD

**Issue by timothycrosley** [Zac-HD/hypothesmith#8]
Hi!

This is a really cool project! I saw the PR posted on the black project [here](https://github.com/psf/black/pull/1566) and was wondering if there would be any interest in helping to integrate it into isort? isort currently has some property testing in place, but only to deal with the complexity around the number of configuration options, and attempting to try many combinations together. However, if you look at the test suite it is riddled with countless parsing issues that unfortunately users found for the project first. I'd love to integrate hypothesmith as part of a strategy to get ahead of future parsing errors.

Thanks!

~Timothy

**Comment by Zac-HD** [comment]
Alright, PR opened!  Let's take any further discussion over there :rocket:
